### PR TITLE
Quickly revert Makefile (but not Cmake) changes

### PR DESCRIPTION
**Pull request by baconpaul**
Revert bd5a250291acf270b38bf447154d1b1b49bcf2e7 for Makefile

### CODE REVIEW

**Comment by baconpaul** [comment]
@qno got a report that our pipeline mac build generates

```
[1.257 info src/plugin.cpp:162 loadPlugin] Loading plugin from /Users/Steve/Documents/Rack2/plugins/SurgeXTRack
[1.358 warn src/plugin.cpp:228 loadPlugin] Could not load plugin /Users/Steve/Documents/Rack2/plugins/SurgeXTRack: Failed to load library /Users/Steve/Documents/Rack2/plugins/SurgeXTRack/plugin.dylib: dlopen(/Users/Steve/Documents/Rack2/plugins/SurgeXTRack/plugin.dylib, 0x0006): symbol not found in flat namespace (__ZN12SurgeStorage29skipPatchLoadDataPathSentinelE)
```

so I reverted the Makefile but not the CMakelists with this change. We can put it back of course but wanted our mac nightly back in the water while we debug to give us time

**Comment by qno** [comment]
Has this error also happened when you run your local development lib in Rack2 on Mac?  Happend this for arm64 or x64?

I'm currently fixing the Mac unused command line warnings and prepare for new Rack-SDK-2.2.1.

I also get now this error when compiling arm64 with the fixed Rack SDK, which seems to be an issue on surge side, I think:

```
In file included from /home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/FxPresetAndClipboardManager.cpp:18:
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/dsp/Effect.h:32:13: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
    virtual ~Effect() { return; }
            ^
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/dsp/Effect.h:32:13: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/FxPresetAndClipboardManager.cpp:352:9: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
        delete t_fx;
        ^
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/FxPresetAndClipboardManager.cpp:352:9: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/FxPresetAndClipboardManager.cpp:430:9: error: aligned deallocation function of type 'void (void *, std::align_val_t) noexcept' is only available on macOS 10.14 or newer
        delete t_fx;
        ^
/home/build/rack-plugin-toolchain/surge-rack2/surge/src/common/FxPresetAndClipboardManager.cpp:430:9: note: if you supply your own aligned allocation functions, use -faligned-allocation to silence this diagnostic
3 errors generated.
make[5]: *** [src/common/CMakeFiles/surge-common.dir/build.make:76: src/common/CMakeFiles/surge-common.dir/FxPresetAndClipboardManager.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
```

**Comment by baconpaul** [comment]
I have a PR in fixing a bunch of warnings and making it compile x86 werror that i'll merge shortly (then I'll get back to work on the actual modules :) )

That ARM problem is one we fixed with a custom new. You need to add -faligned-allocation since we have an aligned allocator.  We define that in surge cmakelist.

The error occurred only in pipeline builds. My local build worked (otherwise I wouldn't have merged it :) )

**Comment by baconpaul** [comment]
Oh I think the solution the toolchain uses to that problem, by the way, is that ARM builds are macOS minimum version 10.15. Since macOS 10.14 doesn't run on ARM machines and the binaries in rack are non-universal that's a fine solution.

**Comment by baconpaul** [comment]
(At least I remember discussing that with cschol a week ago)

Anyway i merged my diffs. I have a working nightly and cmake environment (and the cmake environment is way better) so we can be patient with next sets of changes. I'm going back to writing the modules now.

Thanks again. This is a huge upgrade in my workflow.

**Pull request merged**
