### PR TITLE
Move to latest surge submodule; C++20

### PR DESCRIPTION
**Pull request by baconpaul**

### CODE REVIEW

**Comment by baconpaul** [comment]
@falkTX you had asked me to ping you when surge-rack moves to c++20.  This commit does that. We don't have a surge-rack feature release planned for a while - maybe this summer. 

I tested that the surge vst builds gcc9 and on. We use 9, 11, 12 and 13 in our tests. The surge-rack project builds in the rack toolchain which uses gcc12 on linux.

**Comment by falkTX** [comment]
So Cardinal will be stuck on 2.2.3.0 for a while then, thanks for the update

I mean to do a little pause on Cardinal anyway, we have enough modules already and it is fine to focus on bugfixing instead of doing new stuff.
So FYI very soon Cardinal will enter a feature-freeze sorta state where no new modules are added, lasting until I get all other projects up to speed (so at least a few months).

**Comment by baconpaul** [comment]
yeah i don't have enormous new features for surge-rack planned this summer so staying on 2.2.3.0 is a good strategy

but didn't want to not let you know since you asked!

**Comment by baconpaul** [comment]
ahh well turns out i reverted this change from the rack code. the vcv libc doesn't support enough

i'm pushing ahead with surge and shortcircuit at c++20. just means i will leave the submodule here frozen until folks get to at-least-5-year-old compiler and libc versions.

**Comment by baconpaul** [comment]
and sigh my optimism was misplaced. gcc-11 doesn't reliably support some of the 20-isms i want so i am abandoning the entire move-to-20 project and will just lurk in old-style template hell.

**Pull request merged**
