### PR TITLE
Update to surge, with c++20 requirements

### PR DESCRIPTION
**Pull request by baconpaul**
We may bac this down, but i want to see if it runs in CI then perhaps ask a favor to run through the macos docker toolchain

### CODE REVIEW

**Comment by baconpaul** [comment]
Hi @qno we are debating moving surge to C++20 (or a subset of it). We have it building the vet and also can build the rack plugins on lin docker, win docker, and mac native.

I don't suppose you could check if mac docker can build this can you? I would appreciate it if you have a cycle. If it fails we'll back this down and stay at 17, but clang 12 (which the docker toolchain uses) *should* have enough 20 to compile this.

Thank you as always for any help you may offer.

**Comment by qno** [comment]
Hi, I checked. Result is negative.

```
...
2023-08-05T08:33:49.2177985Z [ 43%] Building CXX object surge/src/common/CMakeFiles/surge-common.dir/FxPresetAndClipboardManager.cpp.o
2023-08-05T08:33:49.2205201Z cd /__w/surge-rack/surge-rack/dep/cmake-build/surge/src/common && /home/build/rack-plugin-toolchain/local/osxcross/bin/arm64-apple-darwin20.2-clang++-libc++ -DGHC_FILESYSTEM_FWD -DGHC_RAISE_UNICODE_ERRORS -DGHC_WIN_WSTRING_STRING_TYPE -DHAS_JUCE=0 -DHAS_LUA=0 -DJUCE_ALLOW_STATIC_NULL_VARIABLES=0 -DJUCE_ALSA=0 -DJUCE_CATCH_UNHANDLED_EXCEPTIONS=0 -DJUCE_COREGRAPHICS_DRAW_ASYNC=1 -DJUCE_DIRECTSOUND=0 -DJUCE_DISPLAY_SPLASH_SCREEN=0 -DJUCE_GLOBAL_MODULE_SETTINGS_INCLUDED=1 -DJUCE_JACK=0 -DJUCE_MODAL_LOOPS_PERMITTED=0 -DJUCE_MODULE_AVAILABLE_juce_audio_basics=1 -DJUCE_MODULE_AVAILABLE_juce_core=1 -DJUCE_MODULE_AVAILABLE_juce_dsp=1 -DJUCE_MODULE_VAILABLE_juce_audio_formats=1 -DJUCE_REPORT_APP_USAGE=0 -DJUCE_STANDALONE_APPLICATION=0 -DJUCE_STRICT_REFCOUNTEDPOINTER=1 -DJUCE_USE_CAMERA=disabled -DJUCE_USE_CURL=0 -DJUCE_USE_FLAC=0 -DJUCE_USE_OGGVORBIS=0 -DJUCE_USE_WINDOWS_MEDIA_FORMAT=0 -DJUCE_VST3_CAN_REPLACE_VST2=0 -DJUCE_WASAPI=0 -DJUCE_WEB_BROWSER=0 -DMAC=1 -DNDEBUG=1 -DSKIP_JUCE=1 -DSQLITE_OMIT_AUTHORIZATION=1 -DSQLITE_OMIT_COMPILEOPTION_DIAGS=1 -DSQLITE_OMIT_DEPRECATED=1 -DSQLITE_OMIT_LOAD_EXTENSION=1 -DSQLITE_OMIT_WAL=1 -DSST_COMMAND_CTRL_SAME_KEY=0 -DSURGE_COMPILE_BLOCK_SIZE=8 -DSURGE_INCLUDE_AIRWINDOWS=0 -DSURGE_SKIP_ODDSOUND_MTS -DTIXML_USE_STL -I/__w/surge-rack/surge-rack/surge/src/common -I/__w/surge-rack/surge-rack/surge/src/common/dsp -I/__w/surge-rack/surge-rack/surge/src/common/dsp/effects -I/__w/surge-rack/surge-rack/surge/src/common/dsp/filters -I/__w/surge-rack/surge-rack/surge/src/common/dsp/modulators -I/__w/surge-rack/surge-rack/surge/src/common/dsp/oscillators -I/__w/surge-rack/surge-rack/surge/src/common/dsp/utilities -I/__w/surge-rack/surge-rack/surge/src/common/dsp/vembertech -I/home/build/rack-plugin-toolchain/Rack-SDK-mac-arm64/dep/include -I/__w/surge-rack/surge-rack/surge/libs/fmt/include -I/__w/surge-rack/surge-rack/surge/libs/libsamplerate/include -I/__w/surge-rack/surge-rack/surge/libs/airwindows/include -I/__w/surge-rack/surge-rack/surge/libs/eurorack/eurorack -I/__w/surge-rack/surge-rack/surge/libs/eurorack/special_include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-cpputils/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-plugininfra/include -I/__w/surge-rack/surge-rack/dep/cmake-build/libs/sst/sst-plugininfra/libs/filesystem/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-plugininfra/libs/strnatcmp -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-plugininfra/libs/tinyxml/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-filters/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-basic-blocks/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-filters/include-extras -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-waveshapers/include -I/__w/surge-rack/surge-rack/surge/libs/sst/sst-effects/include -I/__w/surge-rack/surge-rack/surge/libs/sqlite-3.23.3/. -I/__w/surge-rack/surge-rack/surge/libs/tuning-library/include -I/__w/surge-rack/surge-rack/dep/cmake-build/surge/src/lua/include -I/__w/surge-rack/surge-rack/surge/libs/PEGTL/include -I/__w/surge-rack/surge-rack/surge/src/../libs/JUCE/modules -fPIC -g -O3 -fPIC -march=armv8-a+fp+simd -mmacosx-version-min=10.9 -stdlib=libc++ -O3 -DNDEBUG -arch arm64 -mmacosx-version-min=10.9 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -g -O3 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -march=armv8-a+fp+simd -arch arm64 -Wno-multichar -Werror -fno-char8_t -Wno-unused-command-line-argument -Wno-deprecated-declarations -Werror=inconsistent-missing-override -Werror=logical-op-parentheses -Werror=dynamic-class-memaccess -Werror=undefined-bool-conversion -Werror=bitwise-op-parentheses -Werror=pointer-bool-conversion -Wno-sign-compare -Wno-ignored-qualifiers -Wno-unused-value -Wno-uninitialized -Wno-implicit-fallthrough -Wno-char-subscripts -Wno-unused-local-typedefs -Wno-range-loop-construct -Wno-nonnull -Wno-reorder -Wno-unused-const-variable -Wno-string-concatenation -Wno-class-varargs -Wno-self-assign -Wno-unused-lambda-capture -Wno-mismatched-tags -Wno-infinite-recursion -faligned-allocation -Wno-unused-variable -Wno-unused-private-field -std=c++20 -MD -MT surge/src/common/CMakeFiles/surge-common.dir/FxPresetAndClipboardManager.cpp.o -MF CMakeFiles/surge-common.dir/FxPresetAndClipboardManager.cpp.o.d -o CMakeFiles/surge-common.dir/FxPresetAndClipboardManager.cpp.o -c /__w/surge-rack/surge-rack/surge/src/common/FxPresetAndClipboardManager.cpp
2023-08-05T08:33:49.5527904Z In file included from /__w/surge-rack/surge-rack/surge/src/common/FxPresetAndClipboardManager.cpp:23:
2023-08-05T08:33:49.5535269Z In file included from /__w/surge-rack/surge-rack/surge/src/common/FxPresetAndClipboardManager.h:26:
2023-08-05T08:33:49.5543137Z In file included from /__w/surge-rack/surge-rack/surge/src/common/SurgeStorage.h:25:
2023-08-05T08:33:49.5572983Z /__w/surge-rack/surge-rack/surge/src/common/globals.h:35:18: error: cannot use builtin operator '<=>' because type 'std::strong_ordering' was not found; include <compare>
2023-08-05T08:33:49.5629762Z static_assert((0 <=> 0) == 0, "Surge requires C++20; please update your build.");
2023-08-05T08:33:49.5630119Z  
...
```

See 
[rack-toolchain-mac-x64-build-log.txt](https://github.com/surge-synthesizer/surge-rack/files/12266623/rack-toolchain-mac-x64-build-log.txt)
[rack-toolchain-mac-arm64-build-log.txt](https://github.com/surge-synthesizer/surge-rack/files/12266624/rack-toolchain-mac-arm64-build-log.txt)

**Comment by qno** [comment]
I sent you an invitation to my my private toolchain repo with the MacOs so you can pull and use it locally for checking. If you accept the invitation I need to check if I still need to give you extra credentials.

```
docker pull ghcr.io/qno/rack-plugin-toolchain
```

**Comment by baconpaul** [comment]
Thank you very much! Very useful and I accepted the invite.

**Comment by baconpaul** [comment]
```
paul@pwLinux:~/dev/surge-rack$ sudo docker pull ghcr.io/qno/rack-plugin-toolchain
Using default tag: latest
Error response from daemon: Head "https://ghcr.io/v2/qno/rack-plugin-toolchain/manifests/latest": unauthorized
```
seems still one permission left. I'll try and build an image myself too and see how far i get. thank you!

**Comment by qno** [comment]
OK, I will check, but I also think you need to generate an accress token for baconpaul user as described here https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens and use this token to authenticate with docker.

I have it in my user under Liunx in file `.docker/config.json`

```
{
        "auths": {
                        "ghcr.io": {
                        "auth": "yOuRxxxxToken"
                }
        }
}
```

**Comment by baconpaul** [comment]
hmm yeah so i set up my docker snap so i can run it not sudo and added a tocken and put it there but still no luck. i get unauthorized.

but i also have a copy of the 11.1 sdk and am doing a build of the toolchain on this ubunut box - let me see if that works!

thank you as always

**Comment by qno** [comment]
I see, it looks like this is just possible within an organisation account. I now transfer it to my own registry and give you an throw-away access token for pulling the image ... give me a second to retag the image

**Comment by qno** [comment]
I send you the token via https://community.vcvrack.com private message.

Add it to your docker config

{
        "auths": {
                        "docker.jcr.qx4b.com": {
                        "auth": "yOuRxxxxToken"
                }
        }
}

and run

```
docker pull docker.jcr.qx4b.com/rack-plugin-toolchain
```

**Comment by baconpaul** [comment]
Hmmm no still unauth. Also my ubuntu22 machine failed to build the toolchain! Ahh well.

Anyway I appreciate your help but I think we won't get this todya. The fact that it fails is enough information for now; i'll see if i can do a docker build on my mac of the toolchain - maybe that will work better for me? 
thanks so much though. the failed build is really waht we needed to know.

**Comment by qno** [comment]
I sent you another token, because there ar 2 kinds of tokens to generate.

**Comment by qno** [comment]
Try now - I just enabled anonymous access. remove all the tokens. I will then later disable it again.

Just run `docker pull docker.jcr.qx4b.com/rack-plugin-toolchain`

**Comment by qno** [comment]
OK. I think the problem was that you need to actually use the `docker login` command to authenticate and use then the provided token and not just putting it into the config file.

**Comment by baconpaul** [comment]
OK! Well now it doens't build in the image for another reason .... but my dev is done for the day. Thanks for the help - I may PM you for more if that's OK? I think for now we have to back down back to C++17 though

**Comment by qno** [comment]
Sure.

**Comment by baconpaul** [comment]
Great. and thanks again.

**Pull request merged**
