### PR TITLE
VCF: Use a timer interval instead of threads for emscripten

### PR DESCRIPTION
**Pull request by falkTX**
This PR makes VCF work in web-assembly.

For web-assembly target, using emscripten, using threads is not always wanted.
Threads in web-assembly require a secure connection with special headers, which makes local deploys quite difficult.

What I have been doing for Cardinal is setup timer intervals anytime a thread is used.
There is no well defined API for this on Cardinal side yet though, so a bit of custom code is necessary for now.
Which might be handy if anyone else is building surge-xt-rack in web-assembly too, outside of Cardinal.

Sadly VCF still throws an error later on, I suspect due to some advanced SSE features not all being available in the browser context. But that would be on the surge subproject, not surge-rack.

### CODE REVIEW

**Comment by baconpaul** [comment]
(if you prefer for me to merge it with that caveat i would, since most users won't experience the diminished performance. just let me know either way).

**Comment by baconpaul** [comment]
Ahh I already have the no-animationc ode written

So OK here's the changes I would make

1. Inside the `#if __emscripten__` define a variable with a semantic name like `FILTER_RENDER_ON_SEPARATE_THREAD` which is 1 for everything but 0 for snecripten so we can distinguish between __emscriptn__ and others
2. Keep your change but change the ifdefs to be like
```
#if FILTER_RENDER_ON_SEPARATE_THREAD
   thread = std::make_unique
#else
#if __EMSPCRIPTEN__
   do that timer start
#enif
#else
```

so then we can go ahead and add other timer based approaches in the future

3. Keep your factoring of the render to out of the loop into a separate method. That's a good change. Thank you.
4. Around line 497 you see this code

```
 if (style::XTStyle::getShowModulationAnimationOnDisplay())
        {
            fr = module->modulationAssistant.values[VCF::FREQUENCY][0];
            re = module->modulationAssistant.values[VCF::RESONANCE][0];
            gn = module->modulationAssistant.values[VCF::IN_GAIN][0];
        }
        else
        {
            fr = module->modulationAssistant.basevalues[VCF::FREQUENCY];
            re = module->modulationAssistant.basevalues[VCF::RESONANCE];
            gn = module->modulationAssistant.basevalues[VCF::IN_GAIN];
        }
```

If the THREAD isn't available, you always want to be in the basevalues case. So above that do something like

```
#if FILTER_ANALYZER_OFF_UI_THREAD
   bool useAnim = true;
#else `
   bool useAnim = false
#endif 
```

and make the first diff `useAnim || settings blah`

and then you will minimize your UI thread utilization in a modulated case.

**Comment by baconpaul** [comment]
oh and on the crash. the filter code just uses std sse2 but uses apis which require aligned memory. I've been pretty careful to use alignas and loadu appropriately but i may have missed an alignment in surge-rack clients of the filters. (We think the filters are properly aligned in surge and below since they work on 32 bit windows). Since all our target to date have 16 alignment by default that may be some place to look?

i don't know what the wasm default strategy is.

**Comment by falkTX** [comment]
I like the idea for the no fancy UI drawing, for my current wasm builds everything runs on the same thread so avoiding expensive calculations is always welcome.

regarding alignment, wasm mimics a typical 32bit system with unaligned memory by default, so yes the SSE calls need to be done carefully so they only touch aligned memory.
so far I see the crash inside the quad filter units, triggered by `auto yVec = filterUnitPtr(&filterState, x);`

I have a few other things pending to do which have priority, so will come back to this later.

**Comment by baconpaul** [comment]
right so inside the filter *should* all work fine 32 bit aligned since we run surge proper on the vst. And yes if you run all in one thread you want very much to deactivate the animation of the filter, per the rough outline above. Happy to review again.

sst-filters is a standalone project with a test suite. that may be way way easier to test and debug in emscripten? Also just to eliminate things start with the filter set to "off" and see what happens (which if you need to you can make it do by change the default filter type in VCF.h temporarily). If it crashes at "off" it is one thing, and if theres a particular filter type that crashes etc...

**Comment by falkTX** [comment]
> sst-filters is a standalone project with a test suite. that may be way way easier to test and debug in emscripten

hmm good idea, something for me to try next time.

> If it crashes at "off" it is one thing, and if theres a particular filter type that crashes etc...

from my tests the "off" filter mode works fine, but picking any other triggers issues. it always seem to happen on the timer/thread part, so maybe just disabling animations makes the issue go away. will let you know once I try it.

**Comment by falkTX** [comment]
ok so the tests do fail.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sst-plugininfra-tests.js:1 this.program is a Catch v2.13.7 host application.
sst-plugininfra-tests.js:1 Run with -? for options
sst-plugininfra-tests.js:1 
sst-plugininfra-tests.js:1 -------------------------------------------------------------------------------
sst-plugininfra-tests.js:1 FTZ
sst-plugininfra-tests.js:1 -------------------------------------------------------------------------------
sst-plugininfra-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-plugininfra/tests/tests.cpp:31
sst-plugininfra-tests.js:1 ...............................................................................
sst-plugininfra-tests.js:1 
sst-plugininfra-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-plugininfra/tests/tests.cpp:49: FAILED:
sst-plugininfra-tests.js:1   REQUIRE( res_float[i] == 0 )
sst-plugininfra-tests.js:1 with expansion:
sst-plugininfra-tests.js:1   23 == 0
```

what does this mean?

**Comment by falkTX** [comment]
oh I think I know, you are trying to ensure flush-to-zero actually works so very tiny floats do end up as zero.

**Comment by baconpaul** [comment]
You are running the plugininfra not the filters tests

**Comment by baconpaul** [comment]
But surge has extensive test suits in the surge module and each of the SST su modules 

I would be hesitant to deploy to a new platform if any of those failed 

they all have cmake rules and are catch2 tests

**Comment by baconpaul** [comment]
> oh I think I know, you are trying to ensure flush-to-zero actually works so very tiny floats do end up as zero.

Yeah that’s what that test does

**Comment by falkTX** [comment]
> You are running the plugininfra not the filters tests

right yes. though might as well make sure these pass too.
according to https://emscripten.org/docs/porting/simd.html, the `_mm_setcsr` call is not available so it is not possible to enable FTZ.

apart from that the plugin-infra tests pass.

```
===============================================================================
sst-plugininfra-tests.js:1 All tests passed (59 assertions in 7 test cases)
```

**Comment by baconpaul** [comment]
> > You are running the plugininfra not the filters tests
> 
> right yes. though might as well make sure these pass too. according to https://emscripten.org/docs/porting/simd.html, the `_mm_setcsr` call is not available so it is not possible to enable FTZ.
> 
> apart from that the plugin-infra tests pass.
> 
> ```
> ===============================================================================
> sst-plugininfra-tests.js:1 All tests passed (59 assertions in 7 test cases)
> ```

How do you turn on ftz then?

surge will perform poorly without it

**Comment by baconpaul** [comment]
Or more accurately surge will perform badly if you have software small floats. 

If the runtime can avoid cpu overload with denorms then it should be fine

the combulator the reverbs and the string oscillator will all spike cpu in the deck stages if this is wrong and you want to test

**Comment by falkTX** [comment]
> How do you turn on ftz then?
> 
> surge will perform poorly without it

from the info I find online I do not think it is possible to change this

**Comment by baconpaul** [comment]
> > How do you turn on ftz then?
> > surge will perform poorly without it
> 
> from the info I find online I do not think it is possible to change this

Do denormals end up in a software fp implementation then?

**Comment by falkTX** [comment]
> > > How do you turn on ftz then?
> > > surge will perform poorly without it
> > 
> > 
> > from the info I find online I do not think it is possible to change this
> 
> Do denormals end up in a software fp implementation then?

See https://emscripten.org/docs/porting/simd.html

| - | - |
| _MM_GET_FLUSH_ZERO_MODE | ✅ Always returns _MM_FLUSH_ZERO_OFF. |
| _MM_GET_ROUNDING_MODE | ✅ Always returns _MM_ROUND_NEAREST. |
| _mm_getcsr | ✅ Always returns _MM_FLUSH_ZERO_OFF |
| _MM_ROUND_NEAREST | all exceptions masked (0x1f80). | 
| _MM_SET_EXCEPTION_MASK | ⚫ Not available. Fixed to all exceptions masked. |
| _MM_SET_EXCEPTION_STATE | ⚫ Not available. Fixed to zero/clear state. |
| _MM_SET_FLUSH_ZERO_MODE | ⚫ Not available. Fixed to _MM_FLUSH_ZERO_OFF. |
| _MM_SET_ROUNDING_MODE | ⚫ Not available. Fixed to _MM_ROUND_NEAREST. |
| _mm_setcsr | ⚫ Not available. |

**Comment by falkTX** [comment]
Oh and filter tests do fail.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sst-filters-tests.js:1 this.program is a Catch v2.13.7 host application.
sst-filters-tests.js:1 Run with -? for options
sst-filters-tests.js:1 
sst-filters-tests.js:1 -------------------------------------------------------------------------------
sst-filters-tests.js:1 Cutoff Warp
sst-filters-tests.js:1   Highpass
sst-filters-tests.js:1 -------------------------------------------------------------------------------
sst-filters-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-filters/tests/CutoffWarpTest.cpp:29
sst-filters-tests.js:1 ...............................................................................
sst-filters-tests.js:1 
sst-filters-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-filters/tests/./TestUtils.h:87: FAILED:
sst-filters-tests.js:1   REQUIRE( rmsDB == Approx(testConfig.expRmsDBs[i]).margin(1.0e-2f) )
sst-filters-tests.js:1 with expansion:
sst-filters-tests.js:1   -10.35155f == Approx( -9.8870201111 )

```

**Comment by falkTX** [comment]
Commenting out highpass tests, it then fails on bandpass in a similar way.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sst-filters-tests.js:1 this.program is a Catch v2.13.7 host application.
sst-filters-tests.js:1 Run with -? for options
sst-filters-tests.js:1 
sst-filters-tests.js:1 -------------------------------------------------------------------------------
sst-filters-tests.js:1 Cutoff Warp
sst-filters-tests.js:1   Bandpass
sst-filters-tests.js:1 -------------------------------------------------------------------------------
sst-filters-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-filters/tests/CutoffWarpTest.cpp:73
sst-filters-tests.js:1 ...............................................................................
sst-filters-tests.js:1 
sst-filters-tests.js:1 /home/falktx/Source/DISTRHO/Cardinal.wasm/plugins/surgext/surge/libs/sst/sst-filters/tests/./TestUtils.h:87: FAILED:
sst-filters-tests.js:1   REQUIRE( rmsDB == Approx(testConfig.expRmsDBs[i]).margin(1.0e-2f) )
sst-filters-tests.js:1 with expansion:
sst-filters-tests.js:1   -8.30419f == Approx( -8.0841302872 )
```

Commenting out both highpass and bandpass, all other tests pass.
```
===============================================================================
sst-filters-tests.js:1 All tests passed (894 assertions in 9 test cases)

```

**Comment by baconpaul** [comment]
Is there any way I can run these?

several parts of surge will spin to 100% cpu absent ftz and the fix isn’t thst great - basically reintroduce the noise on the signal to stop denorms from happening. If you choose to pursue thst happy to help guide you. 

If the other tests pass though and run the proximate crash is almost definitely a mis aligned data item in the ui renderer. Hold on

**Comment by baconpaul** [comment]
Curious if you comment out this line

https://github.com/surge-synthesizer/surge-rack/blob/5ac63a84ee8f35a9adecec77b8fb1e77ca316b02/src/VCF.cpp#L400

you won’t get filter viz but then if you run a signal does the filter run?

**Comment by falkTX** [comment]
Tried that already, that part does work :)
And there is proper audio out as far as I can tell.

image

So I am tempted to just disable the filter fancy graph and be done with it.
The web version is still mostly a toy, I am spending way too much time trying to fix something that is not that important in the end..

Let me redo the PR with a simple change to just not have the analyzer at all. And that is good enough for now for web builds in my opinion

**Comment by falkTX** [comment]
> Is there any way I can run these?

Not too complex, https://emscripten.org/docs/getting_started/downloads.html details how to install.
I then just do:

```
source path/to/emsdk/emsdk_env.sh
cd /path/to/sst-filters
emcmake cmake -DSST_FILTERS_BUILD_TESTS=TRUE .
make
```

then make any dumb html code that loads the generate js file, like so:
```
<!doctype html>
<html lang="en-us">
  <head>
    <script async type="text/javascript" src="sst-filters-tests.js"></script>
  </head>
  <body>
  </body>
</html>
```

Then load up the html file on a browser, might need to be served through a web server for security considerations.
Easiest is just `emrun tests/sst-filters-tests.html`

**Comment by baconpaul** [comment]
Yeah I wonder if the filter analyzer also crashed 32 bit windows. I will peek but avoid the problem sounds smartest.  And thanks for info on how to test

**Comment by falkTX** [comment]
ok, PR updated, now much simpler

**Comment by falkTX** [comment]
can you cherry-pick this to the 2.0.x branch? thanks

**Comment by baconpaul** [comment]
Yup will do so later today

**Comment by falkTX** [comment]
updated the web version again, now the filter works on the online version.
you can give it a url to load random patches btw, this one has surge on it https://cardinal.kx.studio/?patchurl=https://kx.studio/Paste/raw/SSkE0

**Comment by baconpaul** [comment]
huh neat. i didn't get any sound and had to launch it in chrome rather than safari but it did render

inasmuch as you care, the pan-to-move gesture in chrome with a mac trackpad is backwards in the app.

the `release-candidate/2.0.4.0` branch now contains this diff.

**Comment by falkTX** [comment]
cool, thanks!

safari doesnt implement wasm simd, so for the moment it doesnt work there.

**Comment by baconpaul** [comment]
yup that's what the message said :)

**Pull request merged**
