### PR TITLE
CMake handle dependencies with interface libraries

### PR DESCRIPTION
**Pull request by qno**
Bundle all dependencies and compiler settings of RackSDK and Surge in interface libraries and only use them on targets that need it and do not pollute all targets with settings from RackSDK.

I think I'm basically done now with the CMake optimizations.

### CODE REVIEW

**Comment by qno** [comment]
Looks like the Mac OS ARM64 build is screwed:
```
/Users/runner/work/surge-rack/surge-rack/surge/src/common/globals.h:44:10: fatal error: 'simde/x86/sse2.h' file not found
#include "simde/x86/sse2.h"
         ^~~~~~~~~~~~~~~~~~
```

I don't know how to fix this, I think it was taking simde before the CMake changes from Rack which is not working anymore, because the surge deps don't know about Rack (includes, etc.) anymore, which is intended.

**Comment by baconpaul** [comment]
Surge has a simde cmake target it links. But thst happens in surge common. If that dep doesn’t percolate up though it’s a problem

so is the surge common dependency on simde public and do you adopt all those deps?

I can pull and look later tonight also or maybe tomorrow but a bit of a busy day or two

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/bd0b1a48385db53b6859b0190e7eaaa298d9af25/src/CMakeLists.txt#L42

I think thst should be cmake current source dir not cmake source dir and that’s why the path is off

il will try that in a bit unless you want to

**Comment by qno** [comment]
I see, it should be `CMAKE_CUURENT_SOURCE_DIR`. I won't fix this. If it is fixed then just run this workflow again and merge it. I'm done with it.

**Comment by baconpaul** [comment]
Yup I’ll pull your changes into a branch and do the submodule shuffle and give it a test. Thanks!

**Comment by baconpaul** [comment]
OK your changes plus the surge fix are now in #733 so closing this one unmerged

**Pull request closed without merging**
