### PR TITLE
Pull Surge to head; turn off MTS in rack build

### LINKED ISSUE #692: Turn Off MTS for Surge-Rack submodule
Per https://github.com/surge-synthesizer/surge/pull/6725

### PR DESCRIPTION
**Pull request by baconpaul**
1. Pull surge to head as a submodule, pulling in all the changes from the weekend

2. Turn off MTS in the Makefile as well as the dep module. Closes #692

### CODE REVIEW

**Comment by baconpaul** [comment]
FYI @falkTX this pulls in all your changes (and a few of mine) to the head of surge-rack. Will merge once CI is done.

Thanks for upstreaming. Glad we could get everything worked out.

**Comment by falkTX** [comment]
Yeah, I just need to swap to an alternative JUCE now.

A couple extra points:
- $(SURGE_BLD)/src/lua/libsurge-lua-src.a is not needed at the moment (makes sense considering -DSURGE_SKIP_LUA=TRUE is in place)
- juce build could be setup so that extra file formats are skipped, reducing binary size `JUCE_USE_FLAC=0 JUCE_USE_OGGVORBIS=0 JUCE_USE_WINDOWS_MEDIA_FORMAT=0` or is there a need for these in surgext?

**Comment by falkTX** [comment]
oh btw, is there any chance of a 2.0.x bugfix branch/release with the latest fixes?
I would swap Cardinal use of surgext to that

**Comment by baconpaul** [comment]
I was waiting until we had been in library for a week or two to get bug reports before deciding that

If you want to though i can make a branch which contains v2.0.3.0 plus

9574063b84e15ab5512afb4730ca2b3b914ae13f
f4be1dd8c3bbc6569218253d3ca1104c7bf4355f
ed1abc54d26262c1c9e0ea0d1862834edee184ee
d8e6994845bcb2e3287f127f7244b5cb3ef061ef

but only the first is needed for rack pro so I dont' know if I would even resubmit to library.

Why don't you make a 2.0.3.0 plus those hashes branch and see if it works and if so I can make it an unsubmitted 2.0.4.0 pretty easily.

**Comment by baconpaul** [comment]
> Yeah, I just need to swap to an alternative JUCE now.
> 
> A couple extra points:
> 
> * $(SURGE_BLD)/src/lua/libsurge-lua-src.a is not needed at the moment (makes sense considering -DSURGE_SKIP_LUA=TRUE is in place)

oh yeah that's smart. i wish i had read that before pressing merge :)

> * juce build could be setup so that extra file formats are skipped, reducing binary size `JUCE_USE_FLAC=0 JUCE_USE_OGGVORBIS=0 JUCE_USE_WINDOWS_MEDIA_FORMAT=0` or is there a need for these in surgext?

there is no need for them no.

**Comment by falkTX** [comment]
I mean I would grab your hotfix/bugfix branch if there was one. I can easily cherry-pick and have a custom hash for the surgext submodule in cardinal, no worries!

**Comment by baconpaul** [comment]
OK let me get the last change in, then you do a test build with the hash list from a cherry pick, and then we decide?

I want to have a 'small' number of tags and branches in our main repos as I'm sure you understand but glad to make one with these diffs if it all works. Lets get it staged first.

**Pull request merged**
