### PR TITLE
Turn off AirWindows unused build; add Install docs

### LINKED ISSUE #652: Turn off the Airwindows build optionally in surge if we aren't going to use it
just to make CI faster and stuff

### LINKED ISSUE #660: Write a little 'how to do an install' doc
including link to library, git push --atomic upstream releases-xt/v2.0.2.0 v2.0.2.0, and more

### PR DESCRIPTION
**Pull request by baconpaul**
1. Bring in the surge diff which turns off airwindows builds optionally and do that in our dep stage to make CI faster. Closes #652
2. Add a small doc on how to prep an install so I don't have to remember those steps next time. Closes #660

### CODE REVIEW

**Comment by qno** [comment]
When airwindows dependency is turned off and I removed it from CMake and Makefile, why is it still build and required?

```
g++ -o plugin.dll build/src/SurgeXT.cpp.o dep/surge-build/libSurgeXTRack.a -Ldep/surge-build/dist/lib/static -lSurgeXTRack -lsurge-common -ljuce_dsp_rack_sub -ltinyxml -lstrnatcmp -lsamplerate -lsst-plugininfra -lfmt -lsqlite -leurorack -lwinmm -luuid -lwsock32 -lshlwapi -lversion -lwininet -lole32 -lws2_32 -shared -L../../../Downloads/Rack-SDK-2.2.1-win-x64/Rack-SDK -lRack -static-libstdc++
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: dep/surge-build/dist/lib/static/libsurge-common.a(AirWindowsEffect.cpp.obj): in function `AirWindowsEffect::AirWindowsEffect(Surg
eStorage*, FxStorage*, pdata*)':
C:/Users/Silvio/Desktop/test/surge-rack/surge/src/common/dsp/effects/airwindows/AirWindowsEffect.cpp:16: undefined reference to `AirWinBaseClass::pluginRegistry()'
C:/tools/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/12.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/Users/Silvio/Desktop/test/surge-rack/surge/src/common/dsp/effects/airwindows/AirWindowsEffect.cpp:17: undefined reference to `
AirWinBaseClass::pluginRegistryOrdering()'
collect2.exe: error: ld returned 1 exit status
make: *** [../../../Downloads/Rack-SDK-2.2.1-win-x64/Rack-SDK/compile.mk:77: plugin.dll] Error 1
```

**Comment by baconpaul** [comment]
There's two parts to airwin

1. The underlying set of 50 or so FX and
2. The 'wrapper' which loads however many are compiled in

Airwindows being turned off means that the compiled in set has size 0 but the wrapper is still there.

So the surge a irwin loader still compiles (although it isn't exposed) but if you did expose and run it it would have no fx in it.

For a (long) variety of reasons this is the easiest way to turn of air windows. There is another option which is we also don't compile the stub loader and then return a newly created equivalent no-op fx, but no reason for that.

**Comment by qno** [comment]
Thanks for expaining.

**Comment by baconpaul** [comment]
Thanks for looking! Really appreciate your work on the project here :)

**Pull request merged**
