### PR TITLE
Namespace fixes for #258

### PR DESCRIPTION
**Pull request by SteveRussell33**
Additionally I can add some comments for some [-Wunused-but-set-variable] warnings. Let me know and I'll add them to this PR.

### CODE REVIEW

**Comment by baconpaul** [comment]
I’m still making sure with @AndrewBelt that he is going to make me put a using namespace into header files to compile. Thanks very much for making this work - I’m going to hold on merging until I head back from him on the issue I lined to 258.

**Comment by SteveRussell33** [comment]
No problem, you're welcome.

**Comment by baconpaul** [comment]
From talking to Andrew over in https://github.com/VCVRack/Rack/issues/1613 We probably want to instead of this change upgrade the azure pipeline to use the latest SDK and just remove the rack::s but verdict still out. Just as an FYI in case you are investing more time here.

And again, appreciate the work!

**Comment by baconpaul** [comment]
If you look at that rack issue, Andrew recommends building against head SDK in our pipelines. That’s sort of a infrastructural PITA but I will get it setup this week I hope. For now I’m going to keep building against the production SDK

I may also just merge your changes - even though I hate them (not your changes per se but putting using into header files is a world of pain which this change has forced us to do). Still deciding.

**Comment by baconpaul** [comment]
Yeah not worth my time to make the pipeline find head. I’ll merge this even though I hate using in header files. Thanks for submitting it.

**Pull request merged**
