### PR TITLE
Update to SDK 2.2.0

### PR DESCRIPTION
**Pull request by qno**
Needed to adapt CI definition after toolchain container update to SDK 2.2.0.

I think I will later "optimize" your Mac build steps  - to much redundancy for my taste  ;-)

### CODE REVIEW

**Comment by qno** [comment]
Regarding the Linux build issue - see here https://github.com/surge-synthesizer/surge-rack/issues/656

So this MR must wait until your Linux build gets fixed.

**Comment by baconpaul** [comment]
Can you hold off on changes here? I have a test build going which should work on linux which includes your initial diff that I want to get merged so cshol can test in his env too.

Your diff looks better than mine and we can certainly apply it once i get merged

**Comment by qno** [comment]
I can just merge your changes - no problem.

**Comment by baconpaul** [comment]
yeah great. i canceled your build so I could get my pipeline done and then we can merge separately with the other improvements here

thanks for all the help by the way. that docker quick start stuff was key to me finding the bug.

**Comment by baconpaul** [comment]
@qno 7900d5d9d9856f420d6435b7d1b640f3873fad63 fixes the linux builds and moves everyone to 2.2.0 but doesn't include the subsequent changes you made here. Sorry to give you a conflict but I wanted to get the changes in cshols hands so we have a chance of getting to the library. Again, gratitude for all the help here. Really appreciated.

**Pull request merged**
