### PR TITLE
Update workflow actions

### PR DESCRIPTION
**Pull request by qno**
See discussion [automated-building-and-releasing-plugins-on-github-with-github-actions](https://community.vcvrack.com/t/automated-building-and-releasing-plugins-on-github-with-github-actions/11364/39?u=qno).

I also removed restrictions to run workflow only on origin repository, because it make no sense to me (except Releases and Nightly workflows).

### CODE REVIEW

**Comment by baconpaul** [comment]
That condition is there to stop the actions running when I sync my fork with the upstream repository. Do you mind reinstating it? Or I will do so before I merge

**Comment by baconpaul** [comment]
But thank you!

**Comment by qno** [comment]
Have you tried to simply disable the workflow on your fork?

See https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow

image

**Comment by baconpaul** [comment]
> Have you tried to simply disable the workflow on your fork?
> 
> See https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
> 
> image

Oh ha that's a way better solution. Thank you!

**Pull request merged**
