### PR TITLE
fix missing symbols for mac and linux plugin

### PR DESCRIPTION
**Pull request by qno**
This fixes the issues of the missing symbols. Looks like linking of all static libs is required for mac and linux as well. I somehow assumed that CMake has already linked this.

I asked here for a test - https://community.vcvrack.com/t/surge-xt-2-1-testing-and-feedback-thread/18813/53?u=qno 

I also needed to reset your -Werror changes, because it was not compiling anymore for me. So you would need to add the changes back again if required.

### CODE REVIEW

**Comment by qno** [comment]
I just checked Linux plugin and it still doesn't load:
```
[1.187 info src/plugin.cpp:128 loadPlugin] Loading plugin from /home/user/.Rack2/plugins/SurgeXTRack
[1.188 warn src/plugin.cpp:194 loadPlugin] Could not load plugin /home/user/.Rack2/plugins/SurgeXTRack: Failed to load library /home/user/.Rack2/plugins/SurgeXTRack/plugin.so: /home/user/.Rack2/plugins/SurgeXTRack/plugin.so: undefined symbol: _ZN3ghc10filesystemneERKNS0_4pathES3_
```

**Comment by qno** [comment]
I found the issue and it is working for Linux, filesystem lib was missing.

**Comment by qno** [comment]
It was confirmed that it is working now on Mac as well - https://community.vcvrack.com/t/surge-xt-2-1-testing-and-feedback-thread/18813/56?u=qno

**Comment by baconpaul** [comment]
Excellent. I have some dev time later this am and will review then.

thank you again

**Comment by baconpaul** [comment]
@qno any reason you undid the surge submodule updgrade out of curiosity? (That was key to making werror work on macOS btw)

it looks good otherwise. I may push a version of this to a fresh PR to include that pull though.

**Comment by baconpaul** [comment]
Oh also you don't turn on C++17 for SurgeXT.cpp. I'll fix that up too.

**Comment by qno** [comment]
Can you please wait, I also have a improvement for the warnings.

**Comment by baconpaul** [comment]
No problem. I pushed my change to your branch with the correct submodule and the C++17 fix.

**Comment by baconpaul** [comment]
I'll be online for another 2.5 hours working on modules at main so just lemme know when you re ready

**Comment by qno** [comment]
Thank you. It seems I always screw up this submodule stuff.

**Comment by qno** [comment]
> Oh also you don't turn on C++17 for SurgeXT.cpp. I'll fix that up too.

It is not needed, because all gets compiled with c++17 in CMAKE. It is just the one cpp that is left to compile with c++11 and it is just complaining about a nested namespace from a include.

**Comment by baconpaul** [comment]
> > Oh also you don't turn on C++17 for SurgeXT.cpp. I'll fix that up too.
> 
> It is not needed, because all gets compiled with c++17 in CMAKE. It is just the one cpp that is left to compile with c++11 and it is just complaining about a nested namespace from a include, the compiler can knows how to handle this.

but it is needed because the nested namespace isn't valid C++17 and the compiler warns :)

So we should turn on C++17 there.

Also there's no reason to expect that I won't use other C++17 idioms in header files it includes!

**Comment by baconpaul** [comment]
> Thank you. It seems I always screw up this submodule stuff.

Submodules are a pain yeah. No worries.

**Comment by qno** [comment]
It is finished from my side.

**Comment by baconpaul** [comment]
OK great thank you!

Exciting.

**Comment by baconpaul** [comment]
Cool i have a couple of tweaks I'll push in my next PR which give us Werror on darwin and also restore debug builds if you turn werror on 

This is awesome. I now have ARM and X86 debug and release options in my clion all working. Fantastic.

**Pull request merged**
