### PR TITLE
updates for Rack-SDK 2.4 changes

### PR DESCRIPTION
**Pull request by qno**
Hi,

I updated all the build related files with required changes for the latest Rack-SDK. 

It is all working also for the latest Rack 2.4.1 SDK and the latest docker toolchain.

### CODE REVIEW

**Comment by qno** [comment]
You can also pull the  updated mac toolchain docker image, it is available exactly as the last time.

**Comment by baconpaul** [comment]
Thanks! Yeah as you saw i did a quick-and-dirty version of this for the 2.4.0 release but appreciate the changes here!

And I actually got the mac toolchain to build on my mac finally, with some help from cshol, so can do that test nicely 

Thanks as always for your efforts.

**Comment by qno** [comment]
May I ask still another question here?

Have you seen with the latest toolchain container (since changes for SDK 2.4.x, image versions 11 or 12) following issues when building for mac with osxcross toolchain:
```
/home/build/rack-plugin-toolchain/Rack-SDK-mac-arm64/arch.mk:17: *** Could not determine CPU architecture of .  Stop.
```
This could also happen with the `mac-x64` compiler.

Sometimes it works in Gitlab CI and when using locally and sometimes it doesn't.

**Comment by baconpaul** [comment]
I have not. I haven’t buckthorn very latest and also run on arm docker ubuntu

**Pull request merged**
