### PR TITLE
Add code-checks to CMakeLists so we can do clformat

### PR DESCRIPTION
**Pull request by baconpaul**

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh @qno I think you are done but please do note this adds another stage to our actions and cmake to bring some of the code checks from surge over to surge-rack. Don't forget to pull to head if you are going to do any more cmake tweakery

And thanks again! Have a lovely weekend and a happy holiday.

**Comment by qno** [comment]
No problem, glad I can help out.

**Comment by qno** [comment]
Btw, have you seen this for your clang-format stuff - https://dev.to/shenxianpeng/cc-lint-action-clang-format-clang-tidy-2o18 ? It will also inline messages in the MR code diff, if I understand this correctly.

I think the checks should at least be moved into its own workflow definition, because it has nothing to do with build-plugin

**Comment by qno** [comment]
I just put together an example PR with default settings of https://github.com/cpp-linter/cpp-linter-action

You can see how it looks like here - https://github.com/qno/surge-rack/pull/1/files

**Comment by baconpaul** [comment]
Oh I’m so used to a single workflow azure style thst I didn’t even think about splitting it. Good idea.

I’ll review this this weekend. I’ve looked at the linter and tidy stuff before but the primary goal here was fail a pr if you are mis formatted like we do for the rest of our builds

**Pull request merged**
