### PR TITLE
Use cmake built plugin

### PR DESCRIPTION
**Pull request by qno**
This is my proposal to build the plugin dist just with CMake and not rebuild it again with Make build.

It basically works, but I'm not sure if this approach is OK.
The only weird thing is that at first call Make creates a "empty plugin" (enforced by `all` target), but it gets immediately overwritten with the cmake built plugin (copied from cmake build), so it doesn't matter.
The trick is to copy the CMake built plugin into the project dir so the dist target is using it and Make doesn't need to build the plugin completely again.

With this it is possible to get rid of all the extra build instructions in the Makefile and have now a generic working Makefile that can just be thrown in a CMake based Rack plugin project for building a proper release. The only thing required to set is the `DISTRIBUTABLES` values.

It is also possible to point Make to an existing CMake build dir by setting `CMAKE_BUILD` variable from outside, so it just uses the plugin from there or it gets build in that folder instead of inside `dep` folder.

Maybe someone with more Make expertise should have a look here as well.

### CODE REVIEW

**Comment by baconpaul** [comment]
Can't review tonight but have some time tomorrow to look.

**Comment by qno** [comment]
OMG - the rebase with origin main screwed up and now it shows files that I haven't touched at all.

**Comment by baconpaul** [comment]
Ahh! Lemme see if I can fix that up for you this morning 

I reset my fork after every merge. Stops drift.

**Comment by baconpaul** [comment]
Independently of the git issues, when I compile with this branch on macOS I get pages of warnings like this at link time:

```
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
```

**Comment by qno** [comment]
OK, let me try first to reset everything.

**Comment by qno** [comment]
I reset the rebase and merge stuff and pushed again, looks good.

**Comment by qno** [comment]
> Independently of the git issues, when I compile with this branch on macOS I get pages of warnings like this at link time:
> 
> ```
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> ```

Was it a clean build?

**Comment by baconpaul** [comment]
OK! Did you get a chance to look at the visibility settings stuff also? If not I can look a bit later today also.

**Comment by qno** [comment]
Here you can check verbose build logs with XCode and osxcross (I have a hidden toolchain container containing oscross compiler).

**Comment by baconpaul** [comment]
> > Independently of the git issues, when I compile with this branch on macOS I get pages of warnings like this at link time:
> > ```
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb4_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb3_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol '__simd128_float32_t sst::waveshapers::CHEBY_CORE<&(sst::waveshapers::cheb2_kernel(__simd128_float32_t)), true>(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::DIGI_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::SINUS_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::ASYM_SSE2(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::CLIP(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ld: warning: direct access in function 'WaveShaperEffect::process(float*, float*)' from file 'surge/src/common/libsurge-common.a(WaveShaperEffect.cpp.o)' to global weak symbol 'sst::waveshapers::TANH(sst::waveshapers::QuadWaveshaperState*, __simd128_float32_t, __simd128_float32_t)' from file 'CMakeFiles/plugin.dir/src/Waveshaper.cpp.o' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> > ```
> 
> Was it a clean build?

ahh it was a not. let me pull and try that.

**Comment by qno** [comment]
Regarding the

> The only weird thing is that at first call Make creates a "empty plugin" (enforced by all target), but it gets immediately overwritten with the cmake built plugin (copied from cmake build), so it doesn't matter.

I solved this by touching an empty plugin lib, so the target is "seen" by make.

**Comment by baconpaul** [comment]
hmmm i still get that symbol error when i do a completely clean build of plugin_quick_install at head of this branch in clion

**Comment by qno** [comment]
I see it also in CI logs now - it's comming probably from the  `-fvisibility=hidden -fvisibility-inlines-hidden`  that is not set for surge build, only for plugin.

**Comment by baconpaul** [comment]
but the surge cmake file sets that as a compile option already

i don't think that's the solution; something is including something out of order somewhere I bet.

**Comment by qno** [comment]
> but the surge cmake file sets that as a compile option already
> 
> i don't think that's the solution; something is including something out of order somewhere I bet.

It sets it only for definitions coming after this, you would have to move this to top of the add_subdirectury (surge).

(I know this because I looked a long time ago  into CMake interpreter code, it is rather primitive, but of course not sure if this is still the case).

**Comment by baconpaul** [comment]
yeah right surge sets it as a global compile_option not as a target option so it is indeed order dependent.

i'm kinda tempted to just put the visibility as a global option at the top of the surge-rack cmake also. You will never not want it. Thoughts?

**Comment by qno** [comment]
> yeah right surge sets it as a global compile_option not as a target option so it is indeed order dependent.
> 
> i'm kinda tempted to just put the visibility as a global option at the top of the surge-rack cmake also. You will never not want it. Thoughts?

Why not - but it can only be set for C++ compiler, you need to check this.

**Comment by baconpaul** [comment]
yeah ok gimme 10 minutes and i'll push up a change or two for your review.

**Comment by baconpaul** [comment]
OK curious on your comments on that diff I just pushed up. Thank you!

**Comment by baconpaul** [comment]
Also if we change `file(INSTALL` to `file(COPY` it does the same thing but is way way way less verbose at cmake output time. That oK with you?

**Comment by qno** [comment]
> Also if we change `file(INSTALL` to `file(COPY` it does the same thing but is way way way less verbose at cmake output time. That oK with you?

I'm fine with this.

**Comment by qno** [comment]
> OK curious on your comments on that diff I just pushed up. Thank you!

The Debug stuff is OK, for the other see my comment.

**Comment by qno** [comment]
> OK curious on your comments on that diff I just pushed up. Thank you!

Looks good to me.

**Comment by baconpaul** [comment]
OK great pushed the INSTALL to COPY change and will merge when CI completes.

Fun fun!

**Comment by qno** [comment]
> OK great pushed the INSTALL to COPY change and will merge when CI completes.
> 
> Fun fun!

Can you hold on? I need to add something back to the README that got lost after I had to undo the weird rebase error.

**Comment by baconpaul** [comment]
No problem! I'm headed out for the afternoon in a bit but can merge when I'm home later today. Just let me know when we're all clear.

**Comment by qno** [comment]
> No problem! I'm headed out for the afternoon in a bit but can merge when I'm home later today. Just let me know when we're all clear.

OK - I'm done - go for it!

**Comment by qno** [comment]
Ok, now!

**Comment by baconpaul** [comment]
Cool i merged

you print that you skip optimizations in the release build :) I'll get that in my next sweep.

**Comment by qno** [comment]
Yeah sure, I did this  ;-)

**Comment by baconpaul** [comment]
Ha yup I fixed it though in the next PR.

Really awesome stuff here. My productivity and tooling is radically improved.

**Pull request merged**
